spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: hendi34
  flyway:
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: postgres
    password: hendi34
  jpa:
    show-sql: true
springdoc:
  api-docs:
    path: /v3/api-docs
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui
application-description: '@project.description@'
application-version: '@project.version@'

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
