spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: hendi34
  flyway:
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: postgres
    password: hendi34
  jpa:
    show-sql: true
